### ISSUE TITLE
One possible mistake in file core/data/data.py 

### ISSUE THREAD

**Issue by yrrIsYourFather** [RL-VIG/LibContinual#11]
I noticed that u apply the code below to define a transformer on dataset Cifar-100, using `STD = [0.2009, 0.1984, 0.2023]`. 
However, as far as I know, the standard deviation for Cifar-100 is [0.2675, 0.2565, 0.2761]. 
Is it a mistake or on purpose? Please let me know. Thx, and nice work!!
```python
MEAN = [0.5071,  0.4866,  0.4409]
STD = [0.2009,  0.1984,  0.2023]

common_trfs = [transforms.ToTensor(),
             transforms.Normalize(mean=MEAN, std=STD)]

resnet_train_transform = transforms.Compose([
  transforms.RandomCrop(32, padding=4),
  transforms.RandomHorizontalFlip(),
  transforms.ColorJitter(brightness=63 / 255),
  *common_trfs
])
```

**Comment by yychen016** [comment]
Hi there,

Thank you for pointing out the discrepancy regarding the standard deviation values used in our transformer setup for the CIFAR-100 dataset. You are correct; the standard deviation values typically cited for CIFAR-100 are `[0.2675, 0.2565, 0.2761]`.

It appears we made a mistake in our configuration. We appreciate your keen observation and bringing this to our attention. We will update our code to use the correct standard deviation values to ensure the transformations are appropriately applied. We will make this correction as soon as possible.

Thanks again for your contribution and for the kind words about our work!

**Comment by yrrIsYourFather** [comment]
thx a lot!
