### ISSUE TITLE
There is a minor error regarding ResNet.

### ISSUE THREAD

**Issue by youandyourself** [RL-VIG/LibContinual#12]
In the file model/backbone/resnet.py, there are only ResNet18 and ResNet34, but in model/der.py, ResNet50 is referenced. When I change the configuration to lucir.yaml in run_trainer.py and run it, an error occurs.

**Comment by yychen016** [comment]
Thank you for bringing this issue to our attention. Indeed, in the file `model/backbone/resnet.py`, we currently only have implementations for `resnet18` and `resnet34`. Unfortunately, `resnet50` was inadvertently removed during a recent codebase cleanup. We apologize for the inconvenience and are working to quickly restore `ResNet50` to the repository.
